name: Publish One Click Apps

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 14
            - run: git config --global url.https://${PERSONAL_TOKEN}@github.com/.insteadOf https://github.com/
            - run: npm ci && npm run publish
              env:
                  GITHUB_PERSONAL_TOKEN: ${{secrets.PERSONAL_TOKEN}}
